### ISSUE TITLE
HSW

### ISSUE THREAD

**Issue by Azulax90** [RuslanUC/aio-hcaptcha#11]

**Comment by RuslanUC** [comment]
You can try using nodejs (pass node="node path" to AsyncHcaptcha instead of executable_path). But sometimes captcha solving fails due to the fact that nodejs doesn't have variables that are available in browsers (for example, window or document objects).

**Comment by Azulax90** [comment]
![image](https://user-images.githubusercontent.com/113309764/201346300-fc7418bc-8916-42ff-aa45-0d8b58b85ee8.png)
I got this error

**Comment by RuslanUC** [comment]
Try installing async-hcaptcha from github
