### ISSUE TITLE
How can I get the rqdata value?

### ISSUE THREAD

**Issue by babalarinthegame** [RuslanUC/aio-hcaptcha#7]
How can I get the rqdata value? I couldn't find anything about it.

**Comment by RuslanUC** [comment]
Rqdata is optional argument. But if you trying to bypass website like discord, you should get rqdata from response. In discord, response looks like {"captcha_sitekey": ..., "captcha_service": "hcaptcha", **"captcha_rqdata": "your rqdara"**, "captcha_rqtoken": ...}. If there is no rqdata in response, then you dont need it.

**Comment by babalarinthegame** [comment]
I will use it on Discord, how can I get it?

**Comment by RuslanUC** [comment]
You should make request without captcha_key, in response will be captcha_rqdata and captcha_rqtoken. After you solve captcha, make request with captcha_key and captcha_rqtoken parameters

**Comment by babalarinthegame** [comment]
Does this value change each time? (One Time/Daily/Daily etc.)
Or do I have to do this every time?

**Comment by RuslanUC** [comment]
Rqdata changes every time because it's base64 of random bytes
