### ISSUE TITLE
Selenium can't be the right Version

### ISSUE THREAD

**Issue by Terribilis1337** [RuslanUC/aio-hcaptcha#8]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hcaptcha-challenger 0.4.2.24 requires selenium~=4.4.3, but you have selenium 4.1.5 which is incompatible.

installing selenium~=4.4.3 ...

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
async-hcaptcha 1.0.0b9 requires selenium~=4.1.5, but you have selenium 4.4.3 which is incompatible.

**Comment by RuslanUC** [comment]
Install async-hcaptcha == 1.0.0b11

**Comment by Terribilis1337** [comment]
Thanks, this solved my issue ^^
